# Generated by Django 4.2.1 on 2023-12-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("discr", models.CharField(max_length=255)),
                ("rag", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="RecentlyDeletedTasks",
        ),
    ]
