# Generated by Django 4.2.1 on 2023-12-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0002_deltask_task_delete_recentlydeletedtasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deltask",
            name="task",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="del_tasks",
                to="taskmanager.task",
            ),
            preserve_default=False,
        ),
    ]
