# Generated by Django 4.2.7 on 2023-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0003_deltask_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
