# Generated by Django 4.2 on 2023-12-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0004_task_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="active",
            field=models.BooleanField(),
        ),
    ]
