# Generated by Django 4.2 on 2024-01-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0006_task_assignee_task_created_on_task_update_last_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deltask",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="del_tasks",
                to="taskmanager.task",
            ),
        ),
    ]
