# Generated by Django 4.2 on 2024-01-22 11:20

from django.db import migrations, models
from django.utils.text import slugify

from taskmanager.models import Task


def create_slug(apps, schema_editor):
    for task in Task.objects.all():
        task.slug = slugify(task.title)
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0011_alter_task_options_delete_deltask"),
    ]
    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(create_slug),
    ]
