# Generated by Django 4.2 on 2024-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0013_addupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
