# Generated by Django 4.2 on 2024-01-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0015_alter_task_the_latest"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.CharField(default="admin", max_length=255),
        ),
    ]
