# Generated by Django 4.2 on 2024-01-26 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0016_task_assignee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="the_latest",
        ),
    ]
